### ISSUE TITLE
only support images ?

### ISSUE THREAD

**Issue by changchichung** [SpotlightKid/nc_share#1]
can I use this program to upload any kind of files to nextcloud and get a public link ?

**Comment by SpotlightKid** [comment]
Yes, I wrote it to upload images (screenshots), but it can upload any kind of files. The default destination directory on the server is set to `xchange/img`, but you can change that via the command line or by changing `DESTDIR` in the source.

**Comment by changchichung** [comment]
OK , thanks for reply , 
but how to install ? is there any install documents ?
I'm not familiar with poetry , is that what you use to manage the package ?

**Comment by changchichung** [comment]
I modify the nc_share.py
update line 11 
```
#from . import nextcloud
import nextcloud
```

and update NEXTCLOUD_URL , DEST_DIR variables .
I can upload files using nc_share.py now , but it doesn't return the public link .

```
(.ve) chchang@hqdc039:~/git/nc_share$ ./nc_share.py pyproject.toml 
Traceback (most recent call last):
  File "./nc_share.py", line 70, in <module>
    sys.exit(main() or 0)
  File "./nc_share.py", line 42, in main
    user = args.user if args.user else getpass.getuser()
NameError: name 'getpass' is not defined
(.ve) chchang@hqdc039:~/git/nc_share$ ./nc_share.py pyproject.toml --password abc123 --user abc
(.ve) chchang@hqdc039:~/git/nc_share$ 
```

the files was uploaded and shared , but does not return a public link
so I still need to login to nextcloud to get the link.

![](https://i.imgur.com/XzbLk70.png)

**Comment by changchichung** [comment]
with verbose parameter , I can see the Share link URL 

```
(.ve) chchang@hqdc039:~/git/nc_share$ ./nc_share.py pyproject.toml --password abc123 --user user  -v
OCS request: GET https://nextcloud.org/ocs/v1.php/cloud/capabilities {'headers': {'OCS-APIREQUEST': 'true'}}
DAV request: PUT /pyproject.toml
Headers:  {'X-OC-MTIME': '1625199266'}
DAV status: 204
OCS request: POST https://nextcloud.org/ocs/v1.php/apps/files_sharing/api/v1/shares {'data': {'shareType': 3, 'path': '/pyproject.toml'}, 'headers': {'OCS-APIREQUEST': 'true'}}
OCS response: apps/files_sharing/api/v1
Share link URL: https://nextcloud.org/index.php/s/ppNBxCBcnJixgFe
(.ve) chchang@hqdc039:~/git/nc_share$ 
```

**Comment by SpotlightKid** [comment]
You don't need poetry, installation is with the usual `pip install .` (note the dot).

The share link is not returned, but placed in the clipboard.
